const KEY='mockmaster_data';
const seed={tests:[{id:'ssc-demo',title:'SSC CGL Quant Mock 01',subject:'Quantitative Aptitude',duration:30,marks:2,negative:.5,questions:[
{q:'If 20% of a number is 48, what is the number?',a:['180','220','240','260'],ans:2,exp:'48 ÷ 0.20 = 240.'},
{q:'A train travels 360 km in 4 hours. Its speed is:',a:['80 km/h','90 km/h','100 km/h','120 km/h'],ans:1,exp:'Speed = 360/4 = 90 km/h.'},
{q:'The average of 10, 20 and 30 is:',a:['15','20','25','30'],ans:1,exp:'(10+20+30)/3 = 20.'}]}],results:[]};
let data=JSON.parse(localStorage.getItem(KEY)||'null')||seed; function save(){localStorage.setItem(KEY,JSON.stringify(data))}
const A=['A','B','C','D']; const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function nav(title){return '<div class="top"><div class="brand">Mock<span>Master</span></div><div class="row"><b>'+esc(title)+'</b><button class="btn secondary" onclick="location.hash=\'\'">Exit</button></div></div>'}
function login(){document.getElementById('app').innerHTML='<div class="login card"><div class="brand">Mock<span>Master</span></div><h2>Online Mock Test Platform</h2><p class="muted">Create and conduct your own online mock tests.</p><div class="field"><label>Student Name</label><input id="name" placeholder="Enter your name"></div><button class="btn" onclick="student()">Continue as Student</button><hr><button class="btn dark" onclick="location.hash=\'#admin\'">Open Admin Panel</button></div>'}
function student(){localStorage.setItem('studentName',document.getElementById('name').value.trim()||'Student');location.hash='#student'}
function studentHome(){let html=nav('Student')+'<div class="wrap"><div class="hero card"><div><h1>Welcome, '+esc(localStorage.getItem('studentName')||'Student')+' 👋</h1><p class="muted">Select a mock test to begin.</p></div></div><div class="card"><h2>Available Tests</h2>'; data.tests.forEach(t=>{html+='<div class="test"><div><span class="pill">'+esc(t.subject)+'</span><h3>'+esc(t.title)+'</h3><p class="muted">'+t.questions.length+' Questions · '+t.duration+' Minutes · +'+t.marks+' / -'+t.negative+'</p></div><button class="btn" onclick="location.hash=\'#test/'+encodeURIComponent(t.id)+'\'">Start Test</button></div>'}); html+='</div></div>'; document.getElementById('app').innerHTML=html}
function adminHome(){let html=nav('Admin Panel')+'<div class="wrap"><div class="hero card"><div><h1>Admin Dashboard</h1><p class="muted">Create mocks, add questions and monitor attempts.</p></div><button class="btn" onclick="newTest()">+ Create Mock</button></div><div class="grid"><div class="stat">Total Mocks<b>'+data.tests.length+'</b></div><div class="stat">Total Questions<b>'+data.tests.reduce((n,t)=>n+t.questions.length,0)+'</b></div><div class="stat">Attempts<b>'+data.results.length+'</b></div></div><div class="card"><h2>Mock Tests</h2>'; data.tests.forEach(t=>{html+='<div class="test"><div><h3>'+esc(t.title)+'</h3><p class="muted">'+t.questions.length+' questions · '+t.duration+' min</p></div><div class="row"><button class="btn secondary" onclick="editTest(\''+esc(t.id)+'\')">Edit</button><button class="btn danger" onclick="deleteTest(\''+esc(t.id)+'\')">Delete</button></div></div>'}); html+='</div><div class="card"><h2>Recent Results</h2><table class="table"><tr><th>Student</th><th>Test</th><th>Score</th><th>%</th></tr>'; if(!data.results.length)html+='<tr><td colspan="4">No attempts yet.</td></tr>'; data.results.slice().reverse().forEach(r=>html+='<tr><td>'+esc(r.student)+'</td><td>'+esc(r.title)+'</td><td>'+r.score+'/'+r.total+'</td><td>'+r.pct+'%</td></tr>'); html+='</table></div></div>';document.getElementById('app').innerHTML=html}
function newTest(){let id=prompt('Unique Test ID:','mock-'+Date.now());if(!id)return;let title=prompt('Mock title:','New Mock Test');if(!title)return;let subject=prompt('Subject:','SSC CGL')||'General';let duration=Number(prompt('Duration (minutes):','60'))||60;let marks=Number(prompt('Marks for correct:','2'))||2;let negative=Number(prompt('Negative marks:','0.5'))||0;data.tests.push({id,title,subject,duration,marks,negative,questions:[]});save();editTest(id)}
function editTest(id){let t=data.tests.find(x=>x.id===id);if(!t)return;let html=nav('Edit Mock')+'<div class="wrap"><div class="card"><h2>'+esc(t.title)+'</h2><p class="muted">Correct answer: A/B/C/D. Add questions one by one or import JSON.</p><button class="btn" onclick="addQ(\''+esc(id)+'\')">+ Add Question</button> <button class="btn secondary" onclick="importJSON(\''+esc(id)+'\')">Import JSON</button></div>'; t.questions.forEach((q,i)=>html+='<div class="card"><b>Q'+(i+1)+'. '+esc(q.q)+'</b><p>A. '+esc(q.a[0])+'<br>B. '+esc(q.a[1])+'<br>C. '+esc(q.a[2])+'<br>D. '+esc(q.a[3])+'</p><span class="pill">Correct: '+A[q.ans]+'</span><button class="btn danger" style="float:right" onclick="delQ(\''+esc(id)+'\','+i+')">Delete</button></div>');html+='</div>';document.getElementById('app').innerHTML=html}
function addQ(id){let q=prompt('Question text:');if(!q)return;let a=[prompt('Option A:'),prompt('Option B:'),prompt('Option C:'),prompt('Option D:')];if(a.some(x=>x===null))return;let c=(prompt('Correct option (A/B/C/D):','A')||'A').toUpperCase();let ans=A.indexOf(c);if(ans<0){alert('Correct option must be A, B, C or D');return}let exp=prompt('Explanation (optional):','')||'';data.tests.find(t=>t.id===id).questions.push({q,a,ans,exp});save();editTest(id)}
function importJSON(id){let raw=prompt('Paste JSON array of questions');try{let qs=JSON.parse(raw);if(!Array.isArray(qs))throw 0;data.tests.find(t=>t.id===id).questions.push(...qs);save();editTest(id)}catch(e){alert('Invalid JSON format')}}
function delQ(id,i){data.tests.find(t=>t.id===id).questions.splice(i,1);save();editTest(id)}
function deleteTest(id){if(confirm('Delete this mock?')){data.tests=data.tests.filter(t=>t.id!==id);save();location.hash='#admin'}}
let ex={};function exam(id){id=decodeURIComponent(id);let t=data.tests.find(x=>x.id===id);if(!t||!t.questions.length){alert('This mock has no questions.');location.hash='#student';return} if(!ex[id])ex[id]={i:0,ans:Array(t.questions.length).fill(null),left:t.duration*60};let s=ex[id],q=t.questions[s.i];let html='<div class="exam"><div class="examhead"><b>'+esc(t.title)+'</b><span class="timer" id="timer">'+fmt(s.left)+'</span><button class="btn" onclick="finish(\''+encodeURIComponent(id)+'\')">Submit Test</button></div><div class="examgrid"><div class="qcard"><p class="muted">Question '+(s.i+1)+' of '+t.questions.length+'</p><h2>'+esc(q.q)+'</h2>';q.a.forEach((x,j)=>html+='<button class="option '+(s.ans[s.i]===j?'selected':'')+'" onclick="answer(\''+encodeURIComponent(id)+'\','+j+')">'+A[j]+'. '+esc(x)+'</button>');html+='<div class="row" style="margin-top:25px"><button class="btn secondary" onclick="move(\''+encodeURIComponent(id)+'\',-1)">Previous</button><button class="btn" onclick="move(\''+encodeURIComponent(id)+'\',1)">Next</button></div></div><div class="palette"><b>Question Palette</b><div class="nums">';t.questions.forEach((_,i)=>html+='<button class="num '+(s.ans[i]!==null?'done ':'')+(i===s.i?'current':'')+'" onclick="gotoQ(\''+encodeURIComponent(id)+'\','+i+')">'+(i+1)+'</button>');html+='</div></div></div></div>';document.getElementById('app').innerHTML=html;clearInterval(window.timer);window.timer=setInterval(()=>{s.left--;let e=document.getElementById('timer');if(e)e.textContent=fmt(s.left);if(s.left<=0){clearInterval(window.timer);finish(id)}},1000)}
function answer(id,j){id=decodeURIComponent(id);ex[id].ans[ex[id].i]=j;exam(id)}function move(id,d){id=decodeURIComponent(id);let s=ex[id],t=data.tests.find(x=>x.id===id);s.i=Math.max(0,Math.min(t.questions.length-1,s.i+d));exam(id)}function gotoQ(id,i){id=decodeURIComponent(id);ex[id].i=i;exam(id)}
function finish(id){clearInterval(window.timer);id=decodeURIComponent(id);let t=data.tests.find(x=>x.id===id),s=ex[id],correct=0,wrong=0;t.questions.forEach((q,i)=>{if(s.ans[i]===q.ans)correct++;else if(s.ans[i]!==null)wrong++});let score=correct*t.marks-wrong*t.negative,total=t.questions.length*t.marks,pct=Math.max(0,score/total*100);let rid='r'+Date.now();data.results.push({id:rid,student:localStorage.getItem('studentName')||'Student',title:t.title,score:+score.toFixed(2),total,pct:+pct.toFixed(2),correct,wrong,unattempted:t.questions.length-correct-wrong,answers:s.ans,testId:id});save();delete ex[id];location.hash='#result/'+rid}
function result(rid){let r=data.results.find(x=>x.id===rid),t=data.tests.find(x=>x.id===r.testId);let html=nav('Result')+'<div class="wrap"><div class="card result"><h1>Test Completed 🎉</h1><div class="score">'+r.score+'</div><p>out of '+r.total+' · '+r.pct+'%</p><div class="grid"><div class="stat">Correct<b>'+r.correct+'</b></div><div class="stat">Wrong<b>'+r.wrong+'</b></div><div class="stat">Unattempted<b>'+r.unattempted+'</b></div></div></div><div class="card"><h2>Solutions</h2>';t.questions.forEach((q,i)=>html+='<div style="padding:14px 0;border-bottom:1px solid #eee"><b>Q'+(i+1)+'. '+esc(q.q)+'</b><p>Your answer: '+(r.answers[i]===null?'Not attempted':A[r.answers[i]])+' · Correct: '+A[q.ans]+'</p><p class="muted">'+esc(q.exp||'No explanation added.')+'</p></div>');html+='</div></div>';document.getElementById('app').innerHTML=html}
function fmt(s){s=Math.max(0,s);return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
function route(){let r=location.hash.slice(1);if(!r)login();else if(r==='student')studentHome();else if(r==='admin')adminHome();else if(r.startsWith('test/'))exam(r.slice(5));else if(r.startsWith('result/'))result(r.slice(7));else login()}window.addEventListener('hashchange',route);route();